<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
{
      "head":{"code":1,"message":""},      
      "value":[{
              "id":"p_1",
              "text":"首页",
              "url":"pages/welcome.html",
              "children":[{
                  "id":"p_11",
                  "text":"进行中任务",
                  "state":"closed",
                  "url":"pages/dataGrid.html",
                  "children":[{
                      "id":"p_111",
                      "text":"任务查询",
                      "url":"pages/dataGrid.html"
                  },{
                      "id":"p_112",
                      "text":"已完成任务",
                      "url":"pages/dataGrid.html"
                  },{
                      "id":"p_113",
                      "text":"企业查询",
                      "url":"pages/dataGrid.html"
                  }]
              },{
                  "id":"p_12",
                  "text":"授权管理",
                  "url":"pages/welcome_test.html",
                  "children":[{
                      "id":"p_121",
                      "text":"接口授权",
                      "url":"pages/welcome_test.html"
                  },{
                      "id":"p_122",
                      "text":"功能授权",
                      "attributes":{
                          "p1":"Custom Attribute1",
                          "p2":"Custom Attribute2"
                      }
                  },{
                      "id":"p_123",
                      "text":"模块授权",
                      "url":"pages/welcome_test.html"
                  },{
                      "id":"p_124",
                      "text":"功能组",
                      "checked":true,
                      "url":"pages/welcome_test.html"
                  }]
              },{
                  "id":"p_13",
                  "text":"个人信息",
                      "url":"pages/welcome_test.html"
              },{
                  "id":"p_14",
                  "text":"修改密码",
                      "url":"pages/welcome_test.html"
              },{
                  "id":"p_15",
                  "text":"功能设置",
                      "url":"pages/welcome_test.html"
              }]
          }],
        "extend":{}
}