{
      "head":{"code":1,"message":""},     
      "value":[{
                "value":1,
                "text":"巡逻特征1"
            },{
                "value":2,
                "text":"巡逻特征2"
            },{
                "value":3,
                "text":"巡逻特征3"
                
            },{
                "value":4,
                "text":"巡逻特征4"
            },{
                "value":5,
                "text":"巡逻特征5"
            }],
      "extend":{}
}