var FrameVersion="20169.8.2158";"object"!==typeof JSON&&(JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function d(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var c=k[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(a,c){var f,k,p,r,v=e,u,t=c[a];t&&"object"===typeof t&&"function"===typeof t.toJSON&&(t=t.toJSON(a));"function"===typeof h&&(t=h.call(c,a,t));switch(typeof t){case "string":return d(t);case "number":return isFinite(t)?String(t):"null";case "boolean":case "null":return String(t);
case "object":if(!t)return"null";e+=g;u=[];if("[object Array]"===Object.prototype.toString.apply(t)){r=t.length;for(f=0;f<r;f+=1)u[f]=b(f,t)||"null";p=0===u.length?"[]":e?"[\n"+e+u.join(",\n"+e)+"\n"+v+"]":"["+u.join(",")+"]";e=v;return p}if(h&&"object"===typeof h)for(r=h.length,f=0;f<r;f+=1)"string"===typeof h[f]&&(k=h[f],(p=b(k,t))&&u.push(d(k)+(e?": ":":")+p));else for(k in t)Object.prototype.hasOwnProperty.call(t,k)&&(p=b(k,t))&&u.push(d(k)+(e?": ":":")+p);p=0===u.length?"{}":e?"{\n"+e+u.join(",\n"+
e)+"\n"+v+"}":"{"+u.join(",")+"}";e=v;return p}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(c){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var c=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,g,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,c,f){var d;g=e="";if("number"===typeof f)for(d=0;d<f;d+=1)g+=" ";else"string"===typeof f&&(g=f);if((h=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return b("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function f(a,c){var e,d,g=a[c];if(g&&"object"===typeof g)for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(d=f(g,e),void 0!==d?g[e]=d:delete g[e]);return b.call(a,c,g)}var e;a=String(a);c.lastIndex=0;c.test(a)&&(a=a.replace(c,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?f({"":e},""):e;throw new SyntaxError("JSON.parse");})})();
(function(a){function d(a,c,f){a.css({"margin-top":"0px","margin-left":"0px"});var e=a.width(),d=a.height();0<e&&0<d&&0<c&&0<f?e!=c&&d!=f&&(d*c/e>f?(d=Math.ceil(d*c/e),e=c):(e=Math.ceil(e*f/d),d=f),c=Math.floor((c-e)/2)+"px",f=Math.floor((f-d)/2)+"px",a.height(d).width(e).css({"margin-top":f,"margin-left":c})):a.css({width:"100%",height:"100%"})}a.extend({getObjectInArray:function(a,c,f){if(isNull(f)||isNull(c))return null;for(var e=0;e<a.length;e++)if(a[e][c]==f)return a[e];return null},getDatagridTd:function(a,
c,f){return a.datagrid("getPanel").find('tr[datagrid-row-index="'+c+'"] td[field="'+f+'"]')},getDatagridLastTd:function(a,c){return a.datagrid("getPanel").find('tr[datagrid-row-index="'+c+'"]:last  td:last')},getDatagridTr:function(a,c){return a.datagrid("getPanel").find('tr[datagrid-row-index="'+c+'"]:last')},slideTo:function(a,c,f,e,d){a&&(e=e||.5,c=c?c:{},f.top=0==f.top?"0px":f.top,f.left=0==f.left?"0px":f.left,c.top=0==c.top?"0px":c.top,c.left=0==c.left?"0px":c.left,f.left?c.left?a.css({left:c.left+
(isNaN(c.left)?"":"px")}):null:null,f.top?c.top?a.css({top:c.top+(isNaN(c.top)?"":"px")}):null:null,a.cssAnimate({left:f.left+(isNaN(f.left)?"":"px"),top:f.top+(isNaN(f.top)?"":"px")},e,null,d))}});a.fn.cssAnimate=function(b,c,f,e,d){a(this).each(function(){var k=a(this);if(supportCss("transition")){var h="",q;for(q in b){var l=q+" "+c+"s "+(f||"")+",";0==q.indexOf("transform")&&(l+="-webkit-"+q+" "+c+"s "+(f||"")+",");h+=l;getComputedStyle(k.get(0))[q]}h=h.substr(0,h.length-1);h=a.extend({},b,{transition:h,
"-webkit-transition":h});d&&0<d&&(h["transition-delay"]=d+"s",h["-webkit-transition-delay"]=d+"s");k.unbind("transitionend webkitTransitionEnd").one("transitionend webkitTransitionEnd",function(){try{"function"==typeof e?e():null}catch(a){console.log(a)}});k.css(h)}else 0<d?k.stop(!0).delay(1E3*d).animate(b,c,f,e):k.stop(!0).animate(b,1E3*c,f,e)});return a(this)};a.fn.endCssAnimate=function(){a(this).each(function(){var b=a(this);b.stop(!0,!0);b.unbind("transitionend webkitTransitionEnd");b.css({transition:"none",
"-webkit-":"none"})});return a(this)};a.fn.beclick=function(b){a(this).unbind("click").bind("click",b);return a(this)};a.fn.rebind=function(b,c){a(this).unbind(b).bind(b,c);return a(this)};a.fn.reone=function(b,c){a(this).unbind(b).one(b,c);return a(this)};a.fn.scrollY=function(b){b=null==b?!0:b;a(this).css({"overflow-y":b?"auto":"hidden"});return a(this)};a.fn.scrollX=function(b){b=null==b?!0:b;a(this).css({"overflow-x":b?"auto":"hidden"});return a(this)};a.fn.toggleSelected=function(b){b=b?b:"nowid";
var c=a(this);c.siblings().removeClass(b);c.addClass(b);return c};a.fn.disableSelect=function(){a(this).css({"-webkit-user-select":"none","-moz-user-select":"none","-khtml-user-select":"none","user-select":"none"}).attr("unselectable","on")};a.fn.del=function(){a(this).clear();a(this).unbind().empty().remove()};a.fn.clear=function(){a(this).each(function(){var b=a(this).get(0);a("*",b).add([b]).each(function(){a.event.remove(this);a.removeData(this)});b.innerHTML?b.innerHTML="":null});return a(this)};
a.fn.enter=function(b){a(this).unbind("keydown").bind("keydown",function(a){13==a.keyCode&&b()});return a(this)};a.fn.changeValue=function(b){var c,f=a(this);"radio"==f.attr("type")?f.each(function(){a(this).get(0).checked&&(c=a(this).val())}):"checkbox"==f.attr("type")?(f.each(function(){a(this).get(0).checked&&(c+=a(this).val()+",")}),1<c.length&&(c=c.substr(0,c.length-1)),"object"==typeof b&&(c=c.split(","))):c=f.val();if(!compare(b,c)&&(isNull(b.value)||b.value!=c)){if("radio"==f.attr("type")){var e=
!1;"object"==typeof b&&(b=b[0]);f.each(function(){a(this).get(0).value==b?(e=a(this).get(0).checked=!0,a(this).change()):a(this).get(0).checked=!1});e||f.change()}else if("checkbox"==f.attr("type"))"string"==typeof b&&(b=b.split(",")),f.val(b).change();else if("object"!=typeof b||isNull(b.text)||isNull(b.value))f.val(b).change();else{var d=f.data("textinput");d&&d.val(b.text);f.val(b.value).change()}return f}};a.fn.checkPower=function(){if(!CHECKPOWER)return!0;var b=a(this).powerFlag();return WINDOW.checkPower(b)};
a.fn.powerFlag=function(b){var c="",f=a(this);if(b){if(a.isArray(b)){for(var e=0;e<b.length;e++)c+=b[e]+"|";1<c.length&&(c=c.substr(0,c.length-1))}else"string"==typeof b&&(c=b);if(c)return f.attr("data-allow",c),c.split("|");f.removeAttr("data-allow");return null}return(b=trim(f.attr("data-allow")))&&"undefined"!=b?b.split("|"):null};a.fn.dataOptions=function(b,c){c=c?c:"data-option";if(b)try{var f=JSON.stringify(b),f=f.replace(/\"/g,"'");a(this).attr(c,f)}catch(d){}else{var e={},f=a(this).attr(c)+
"";try{f=f.replace(/\'/g,'"'),e=JSON.parse(f)}catch(d){}return e}};a.fn.getDataOptions=function(b){return a(this).dataOptions(null,b)};a.fn.setRealSize=function(b,c){a(this).each(function(){var f=a(this);b&&f.width(Math.floor(b-(f.outerWidth(!0)-f.width())));c&&f.height(Math.floor(c-(f.outerHeight(!0)-f.height())))});return a(this)};a.fn.fillParent=function(){a(this).each(function(){var b=a(this),c=b.parent().css("overflow");b.parent().css("overflow","hidden");var f=b.parent().width(),e=b.parent().height();
b.setRealSize(f,e);b.parent().css("overflow",c)});return a(this)};a.fn.centerInWindow=function(){a(this).css({left:Math.floor((a(window).width()-a(this).width())/2)+"px",top:Math.floor((a(window).height()-a(this).height())/2)+"px"});return a(this)};a.fn.getCenter=function(){var b=a(this).offset();return[Math.floor(b.left+a(this).outerWidth(!0)/2)-a(window).scrollLeft(),Math.floor(b.top+a(this).outerHeight(!0)/2)-a(window).scrollTop()]};a.fn.getBounce=function(){var b=a(this).offset();return{x:Math.floor(b.left-
a(window).scrollLeft()),y:Math.floor(b.top-a(window).scrollTop()),w:Math.floor(a(this).outerWidth()),h:Math.floor(a(this).outerHeight())}};a.fn.getMinSize=function(){var b=a(this),c=b.css("min-width")+"",f=b.css("min-height")+"",e=b.css("width")+"",d=b.css("height")+"",c=parseInt(c.replace("px",""))||0,f=parseInt(f.replace("px",""))||0,e=parseInt(e.replace("px",""))||0,d=parseInt(d.replace("px",""))||0,k=b.get(0).style.flex+"",h=k.split(" "),k=k?Number(h[0])||0:0,q=0;k&&"NaN"!=k?(e=c||0,d=f||0,b.css({"-ms-flex":k+
" "+(h[1]||1)+" "+(h[2]||"auto")}),h[2]&&(q=parseInt(h[2].replace("px","")),e=Math.max(e,q),d=Math.max(d,q))):(e=Math.max(e,c),d=Math.max(d,f));return{minw:e,minh:d}};a.fn.fillFont=function(b){a(this).each(function(){var c=a(this);if(!c.data("fillfont")){var f=new fillWraperFont(c,b);c.data("fillfont",f)}})};a.fn.resizeFillFont=function(){a(this).each(function(){var b=a(this).data("fillfont");b&&"function"==typeof b.resize&&b.resize()})};a.fn.fitImg=function(){a(this).each(function(){var b=a(this).width(),
c=a(this).height(),f=a(this).find(">img:eq(0)");if(0!=f.length){var e;a(this).hasClass("fm_piccut")?e=a(this):(e=a('<div class="fm_piccut"></div>'),f.after(e),e.css("overflow","hidden").width(b).height(c),e.append(f));f.get(0).complete?d(f,b,c):(f.one("load",function(){d(f,b,c)}).one("error",function(){f.remove();e.addClass("fm_imagerror")}),f.get(0).src=f.get(0).src)}});return a(this)};a.fn.getDatagridSelectedIds=function(b){for(var c=a(this).datagrid("getChecked"),f="",e=0;e<c.length;e++)f+=c[e][b]+
",";0<f.length&&(f=f.substr(0,f.length-1));return f};a.fn.DropDown=function(b){var c=a(this).eq(0);if(0!=c.length){var f=c.dataOptions();a.extend(f,b);f.action=f.action?"mouseenter"==f.action?"mouseenter":"click":"click";f.hideaction="mouseenter"==f.action?"mouseleave":"click";if(f){c.css({position:"relative"});var e=c.find("#"+f.dropid);b=e.outerWidth()-e.width();e.hide();e.css({position:"absolute",top:c.outerHeight()-2+"px",left:"0px","min-width":c.outerWidth()-b+"px","z-index":9999});var d=function(){e.unbind().stop().slideUp("fast");
e.removeClass("open");c.unbind(f.hideaction)};c.bind(f.action,function(){if(e.hasClass("open")&&"click"==f.action)d();else{e.stop().slideDown("fast").addClass("open");e.one("mouseleave",d);if("mouseenter"==f.action)c.one(f.hideaction,d);if(f.hidebyclick)e.one("click",d)}})}}};a.fn.AccordionFrame=function(b){var c=a(this),f=c.find(">*");f.each(function(){var c=a(this).dataOptions(),b=a('<div class="fm_AccordionBar"><i class="fa fa-angle-down"></i> '+(c.title||"")+"</div>");a(this).before(b);c.open?
b.addClass("open").find("i").attr("class","fa fa-angle-up"):a(this).hide()});var e=c.find(">div.fm_AccordionBar");0==e.length&&(e.eq(0).addClass("open").find("i").attr("class","fa fa-angle-up"),f.eq(0).show());e.bind("click",function(){var c=e.index(a(this));a(this).hasClass("open")?(a(this).removeClass("open").find("i").attr("class","fa fa-angle-down"),f.eq(c).hide()):(b&&(e.removeClass("open").find("i").attr("class","fa fa-angle-down"),f.hide()),a(this).addClass("open").find("i").attr("class","fa fa-angle-up"),
f.eq(c).show())})}})(jQuery);function getDateString(a){a||(a=new Date);return a.getFullYear()+"-"+(a.getMonth()+1)+"-"+a.getDate()+" "+a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()}function delHostUrl(a){var d=window.location.href.split("://")[0]+"\\:\\/\\/"+window.location.host.replace(/\:/g,"\\:");return a=a.replace(eval("/"+d+"/g"),"")}function trim(a){return isNull(a)?"":(a+"").replace(/^\s*|\s*$/g,"")}
function delBlank(a){return isNull(a)?"":(a+"").replace(/(\s+)$/g,"").replace(/\s+/g,"")}function delHtmlTag(a){return a.replace(/<[^>]+>/g,"")}function delReturn(a){a=a.replace(/[\n]/ig,"");return a=a.replace(/[\r]/ig,"")}function addCookie(a,d,b){a=a+"="+escape(d);b=b?b:0;0<b&&(d=new Date,b*=36E5,d.setTime(d.getTime()+b),a+="; expires="+d.toGMTString());document.cookie=a+"; path=/"}
function getCookie(a){for(var d=document.cookie.split("; "),b=0;b<d.length;b++){var c=d[b].split("=");if(c[0]==a)return unescape(c[1])}}function delCookie(a){var d=new Date;d.setTime(d.getTime()-1E4);document.cookie=a+"=a; expires="+d.toGMTString()+"; path=/"}function allCookie(){return document.cookie}function saveToLocal(a,d){var b="string"==typeof d?d:JSON.stringify(d);window.localStorage?window.localStorage.setItem(a,b):addCookie(a,b,43800)}
function readFromLocal(a){var d="",d=window.localStorage?window.localStorage.getItem(a):getCookie(a);try{d=JSON.parse(d)}catch(b){}return d}function removeLocal(a){window.localStorage?window.localStorage.removeItem(a):delCookie(a)}function stopPP(a){a=a||window.event;a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function HTMLEncode(a){var d=document.createElement("div");null!=d.textContent?d.textContent=a:d.innerText=a;return d.innerHTML}
function formatHtml(a){try{var d=$(a),b=$("<div></div>");b.append(d);var c=b.html();b.empty().remove();return c}catch(f){return""}}function Html2Str(a){try{var d=$("<div></div>");d.text(a);var b=d.text();d.empty().remove();return b}catch(c){return""}}function formatSqlStr(a){try{return a.replace(/\</g,"&lt;").replace(/\>/g,"&gt;").replace(/\"/g,"&quot;").replace(/\'/g,"&apos;")}catch(d){console.log(d)}return""}
function HTMLDecode(a){var d=document.createElement("div");d.innerHTML=a;return d.innerText||d.textContent}function creatCode(a,d){for(var b="",b=""+(new Date).getTime(),b=b.substr(d,b.length),b=Math.floor(100*Math.random())+""+b,c="",f=0;f<b.length;f++)c=0==f%2?c+a.substr(b[f],1):c+(b[f]+"");return c}function delSelect(a){$("select[name="+a+"]").find("option").each(function(){1==$(this).get(0).selected&&$(this).remove()})}
function delSelectOption(a){a.find("option").each(function(){1==$(this).get(0).selected&&$(this).remove()})}function mergeJson(a){try{return $.extend({},a)}catch(d){return null}}function cloneJson(a){try{return JSON.parse(JSON.stringify(a))}catch(d){try{return $.extend(!0,{},a)}catch(b){return null}}}function inArray(a,d){for(i=0;i<a.length;i++)if(a[i]==d)return!0;return!1}
function getDateFromStr(a){if(!a||""==a)return null;a=a.split("-");var d=new Date;a[0]&&d.setYear(parseInt(a[0]));a[1]&&d.setMonth(parseInt(a[1]-1));a[2]&&d.setDate(parseInt(a[2]));return d}function getDateStingForce2(a){return a.getFullYear()+"-"+formatTo2(a.getMonth()+1)+"-"+formatTo2(a.getDate())}
function getDateTimeStingForce2(a){return a.getFullYear()+"-"+formatTo2(a.getMonth()+1)+"-"+formatTo2(a.getDate())+" "+formatTo2(a.getHours())+":"+formatTo2(a.getMinutes())+":"+formatTo2(a.getSeconds())}function formatTo2(a){a="0"+a;return a.substr(a.length-2,2)}function getObjectValue(a){if("string"==typeof a)if(0==a.indexOf("[")||0==a.indexOf("{")){a=a.replace(/\'/g,'"');try{a=JSON.parse(a)}catch(d){a=null}}else a=""===a?null:a.split(",");return a}
function getArrayFromString(a,d){if(""==a)return[];if("string"==typeof a)if(d=d?d:",",0==a.indexOf("["))try{return JSON.parse(a)}catch(b){return a.split(d)}else return a.split(d);else if($.isArray(a))return a;return[]}function cutArrayStringTail(a){if(0==a.length)return a;for(;","==a.substr(a.length-1,1);)a=a.substr(0,a.length-1);return a}
function getQueryString(a){a=new RegExp("(^|&)"+a+"=([^&]*)(&|$)","i");a=decodeURI(window.location.search).substr(1).match(a);return null!=a?unescape(a[2]):null}function delInputHtml(){var a=$(this);a.css("opacity",.01);setTimeout(function(){var d=trim(a.html()+""),d=clearHtml(d);a.html(d);a.css("opacity",1)},30)}
function clearHtml(a){var d=$("<div></div>"),b="/\\<\\/div\\>\\<div\\>/g /\\<\\/DIV\\>\\<DIV\\>/g /\\<div\\>/g /\\<DIV\\>/g /\\<\\/div\\>/g /\\<\\/DIV\\>/g /\\<\\/p\\>\\<p\\>/g /\\<\\/P\\>\\<P\\>/g /\\<br\\>/g /\\<BR\\>/g /\\<br\\/\\>/g /\\<BR\\/\\>/g".split(" ");str=a;browserIsOpera&&(str=str.replace(/\<div\>\<br\>\<\/div\>/g,"###br###"),str=str.replace(/\<div\>\<br\/\>\<\/div\>/g,"###br###"));for(a=0;a<b.length;a++)str=str.replace(eval(b[a]),"###br###");d.html(str);str=d.text()+"";return str=str.replace(/###br###/g,
"<br/>")}
function formatHtml(a){var d="/\\<\\/div\\>\\<div\\>/g /\\<\\/DIV\\>\\<DIV\\>/g /\\<div\\>/g /\\<DIV\\>/g /\\<\\/div\\>/g /\\<\\/DIV\\>/g /\\<\\/p\\>\\<p\\>/g /\\<\\/P\\>\\<P\\>/g /\\<br\\>/g /\\<BR\\>/g /\\<br\\/\\>/g /\\<BR\\/\\>/g".split(" ");str=a;browserIsOpera&&(str=str.replace(/\<div\>\<br\>\<\/div\>/g,"###br###"),str=str.replace(/\<div\>\<br\/\>\<\/div\>/g,"###br###"));for(a=0;a<d.length;a++)str=str.replace(eval(d[a]),"###br###");str=Html2Str(str);str=formatSqlStr(str);return str=str.replace(/###br###/g,
"<br/>")}function isNull(a){return null==a||"undefined"==typeof a?!0:!1}function getObjectName(a){for(var d in window)if(window[d]==a)return d.toString();return null}
function compare(a,d){var b=/undefined|number|string|boolean/,c=/^(function\s*)(\w*\b)/,f=arguments.callee;if(null===a&&null===d)return!0;if(b.test(typeof a)||b.test(typeof d)||null===a||null===d)return(null===a||"undefined"==typeof a?"":a).toString()===(null===d||"undefined"==typeof d?"":d).toString();if(a.constructor!==d.constructor)return!1;switch(a.constructor){case Date:return a.valueOf()===d.valueOf();case Function:return a.toString().replace(c,"$1")===d.toString().replace(c,"$1");case Array:if(a.length!==
d.length)return!1;for(var e=0;e<a.length;e++)if(!f(a[e],d[e]))return!1;break;default:c=b=0;if(a===d)break;if(a.childNodes||a.parentNode||d.childNodes||d.parentNode)return a===d;for(e in a)b++;for(e in d)c++;if(b!==c)return!1;for(e in a)if(!f(a[e],d[e]))return!1}return!0}function destroyDom(a){a&&a.each(function(){var a=$(this).get(0);$("*",a).add([a]).each(function(){$.event.remove(this);$.removeData(this)});a.innerHTML=""})}
function flashChecker(){var a=0,d=0;if(document.all){var b;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){return{f:0,v:0}}if(b)a=1,VSwf=b.GetVariable("$version"),d=parseInt(VSwf.split(" ")[1].split(",")[0]);else return{f:0,v:0}}else if(navigator.plugins&&0<navigator.plugins.length&&(b=navigator.plugins["Shockwave Flash"])){a=1;b=b.description.split(" ");for(var c=0;c<b.length;++c)isNaN(parseInt(b[c]))||(d=parseInt(b[c]))}return{f:a,v:d}}
function supportCss(a){var d=["webkit","Moz","ms","o"],b,c=[],f=document.documentElement.style,e=function(a){return a.replace(/-(\w)/g,function(a,c){return c.toUpperCase()})};for(b in d)c.push(e(d[b]+"-"+a)),c.push(e(a));for(b in c)if(c[b]in f)return!0;return!1}function getPicRealSize(a){var d=new Image;d.src=a.attr("src");return{width:d.width,height:d.height}}
function isScroll(a){if("hidden"==a.get(0).style.overflow||"hidden"==a.get(0).style.overflowY)return!1;var d=a.scrollTop();if(0<d)return!0;a.scrollTop(10);d=a.scrollTop();return 0<d?(a.scrollTop(0),!0):!1}function getScrollBarWidth(){var a=$("<div></div>");a.height($(window).height()+100);$("body").append(a);$("body").hide();var d=$(window).width();$("body").show();var b=$(window).width();a.remove();return d-b}
function fillWraperFont(a,d){var b=this;this.option={min:1,max:9999,length:1};this.install=function(){$.extend(b.option,d);b.resize()};this.resize=function(){var c=a.width(),c=Math.floor(c/b.option.length),f=a.height();0!=c&&0!=f&&(c=Math.floor(Math.min(c,f)),c=c<b.option.min?b.option.min:c>b.option.max?b.option.max:c,a.css({"font-size":c+"px","line-height":f+"px"}))};this.install()}
function dateDiff(a,d,b){var c={D:864E5,H:36E5,M:6E4,S:1E3,T:1};a=a.toUpperCase();d=Date.parse(d.replace(/-/g,"/"));b=Date.parse(b.replace(/-/g,"/"));try{return Math.round((b-d)/c[a])}catch(f){return f.message}}function checkArrayDeep(a,d,b){d=d||"children";for(var c=b=b||1,f=!1,e=0;e<a.length;e++)a[e][d]&&0<a[e][d].length&&(f||(b++,c++,f=!0),b=Math.max(b,checkArrayDeep(a[e][d],d,c)));return b}
(function(a,d,b){function c(){g=d.setTimeout(function(){f.each(function(){var c=a(this),b=c.width(),f=c.height(),e=a.data(this,"resizediv-special-event");!e||b===e.w&&f===e.h||c.trigger("resizediv",[e.w=b,e.h=f])});c()},e.delay)}var f=a([]),e=a.resize=a.extend(a.resizediv,{}),g;e.delay=250;e.throttleWindow=!0;a.event.special.resizediv={setup:function(){if(!e.throttleWindow&&this.setTimeout)return!1;var b=a(this);f=f.add(b);a.data(this,"resizediv-special-event",{w:b.width(),h:b.height()});1===f.length&&
c()},teardown:function(){if(!e.throttleWindow&&this.setTimeout)return!1;var c=a(this);f=f.not(c);c.removeData("resizediv-special-event");f.length||clearTimeout(g)},add:function(c){function f(c,e,g){var h=a(this),k=a.data(this,"resizediv-special-event");k&&(k.w=e!==b?e:h.width(),k.h=g!==b?g:h.height(),d.apply(this,arguments))}if(!e.throttleWindow&&this.setTimeout)return!1;var d;if(a.isFunction(c))return d=c,f;d=c.handler;c.handler=f}}})(jQuery,this);
function getIndex(a){return"object"==typeof ZINDEX?ZINDEX[a]||99999:99999}
(function(a){function d(c,b){var e="";switch(b){case "confirm":e="fa fa-question-circle";break;case "success":e="fa fa-check-circle";break;case "alert":e="fa fa-exclamation-circle";break;case "error":e="fa fa-times-circle";break;default:e="fa fa-warning"}var e=a('<div class="fm_alertContentDiv '+b+'"><i class="'+e+'"></i></div>'),d=a("<div></div>");c=HTMLDecode(c).replace(/\n/g,"<br/>");d.html(c);e.append(d).append(a('<p><a class="confirmbut" >\u786e\u5b9a</a>'+("confirm"==b?'<a class="cancelbut" >\u53d6\u6d88</a>':
"")+"</p>"));return e}function b(c,b,e){var g=new popMask(getIndex("messager")-1),k=d(c,b||"alert");a("body").append(k);k.getFitSize(a(window).width()/a(window).height(),180);var h=new dragDivObj;h.install(k,k);var q=new CenterInWindow(k);k.css("z-index",getIndex("messager"));var l=function(c){k?13!=c.keyCode&&27!=c.keyCode||m(13==c.keyCode):a(document).unbind("keydown",l)},m=function(c){a(document).unbind("keydown",l);h.stopDrag();h=null;q.destroy();q=null;k.remove();k=null;g.destroy();g=null;"function"==
typeof e&&e(c)};a(document).one("keydown",l);k.find("p a").bind("click",function(){m(a(this).hasClass("confirmbut"))})}a.extend({alert:function(a){b(a)},confirm:function(a,f){b(a,"confirm",f)},success:function(a){b(a,"success")},errormsg:function(a){b(a,"error")},loading:function(a,b){var e=new loadingRoll;a&&setTimeout(function(){try{e.destroy()}catch(a){}},a);e.show(b)},loaded:function(){a(document).trigger("CLEAR_MASK").trigger("HIDE_LOADING")},progress:function(c,b){var e=a("#fm_loading");0==
e.length?(e=new loadingRoll,e.show(b)):e=e.data("loadobj");try{e.progress(c)}catch(d){}},message:function(c,b){b=0<b?b:2E3;a("#fm_popShowMessage").stop().remove();var e=a('<div id="fm_popShowMessage">'+HTMLDecode(c)+"</div>");a("body").append(e);e.css({position:"fixed",bottom:"0px",padding:"8px",width:"70%","text-align":"center","z-index":getIndex("messager"),"background-color":"#000",color:"#fff","border-radius":"4px",opacity:0,"font-size":"12px","max-width":"800px","box-shadow":"0px 0px 5px #000",
"max-height":a(window).height()-100+"px","overflow-y":"auto","overflow-x":"hidden"});e.css("left",(a(window).width()-e.outerWidth(!0))/2+"px");e.animate({bottom:"50px",opacity:.7},800).delay(b).fadeOut("slow",function(){e.stop().remove()}).bind("mousedown",function(){e.stop().remove()})},lockMask:function(a,b,e){a=new popMask(a);e?a.name=e:null;b&&setTimeout(a.destroy,b);return a},clearMask:function(c){a(".fm_Mask").each(function(){try{var b=a(this).data("obj");b.name==c&&(b.destroy(),a(this).del())}catch(e){}})},
clearAllMask:function(){a(".fm_Mask").each(function(){try{a(this).data("obj").destroy()}catch(c){}a(this).del()})},popMessage:function(a,b,e,d,k,h){new popOutSelfMsg(a,b,e,d,k,h)},clearPopMessage:function(){a(document).trigger("HIDE_MSG")},slideUpMessage:function(c,b,e,d,k,h){k=k?k:0;var q=getIndex("popMsg"),l=a("body").find(".fm_slideUpMsgWindow"+(h?"#"+h:""));if(0<l.length){try{l.data("destroy")()}catch(v){}l.remove();l=null}l=a('<div class="fm_slideUpMsgWindow" id="'+h+'"><div class="fm_slmsgTitle bkflash"><a  style="float:right"><i class="fa fa-remove"/></a><i class="fa fa-comment"/>\u6d88\u606f\u63d0\u9192</div><div class="fm_slmsgContent" style="overflow:hidden"></div></div>');
l.css({position:"fixed",right:k+"px",bottom:"0px","z-index":q});a("body").append(l);var m=l.find(".fm_slmsgContent");m.append(c);m.height(0).width(b[0]).animate({height:b[1]},600);var n,p;d&&(n=new popMask(q-1));var r=function(c,b){b&&b.msgId&&h&&b.msgId!=h||(p&&(clearTimeout(p),p=null),l&&(n&&(n.destroy(),n=null),a(document).unbind("HIDE_SLIDE_MSG",r),m.stop().del(),l.del(),l=null))};l.data({destroy:r,id:h});a(document).bind("HIDE_SLIDE_MSG",r);l.find(".fm_slmsgTitle a").bind("click",r);0<e&&(p=
setTimeout(r,e))},closeSlideUpMessage:function(c){a(document).trigger("HIDE_SLIDE_MSG",{msgId:c})},closetips:function(){a(".fm_popShowTips").stop().each(function(){try{a(this).data("destroy")()}catch(c){}a(this).del()})},tips:function(c,b,e,d,k){k=k?k:2E3;var h,q;if(c){if(c.html||c.innerHTML)try{var l=a(c).getBounce();switch(b){case "left":h=[l.x,Math.floor(l.y+l.h/2)];break;case "right":h=[l.x+l.w,Math.floor(l.y+l.h/2)];break;case "top":h=[Math.floor(l.x+l.w/2),l.y];break;case "bottom":h=[Math.floor(l.x+
l.w/2),l.y+l.h]}}catch(u){return}else if(a.isArray(c))h=c;else return;a.closetips();b=b?b:"top";var m=a('<div class="fm_popShowTips"><div class="relpos"></div></div>'),l=a('<div class="fm_arrow arrow_'+b+'"></div></div>');c=a('<span><i class="fa fa-remove"></i></span>');m.find(".relpos").append(l).append(c);var n=a('<div class="fm_tipsContent" style="padding:8px"></div>');e="function"==typeof e?e():e;"object"==typeof e?n.append(e):n.html(e+"");a("body").append(m);m.append(n);d?(d[0]?n.width(d[0]):
null,d[1]?n.height(d[1]):null):n.getFitSize(4/3,80);m.css({position:"absolute","z-index":getIndex("tips")});l.css({position:"absolute"});c.css({position:"absolute",cursor:"pointer",display:"block",width:"16px",height:"16px","line-height":"16px","font-size":"14px","text-align":"center",color:"#e68546"}).find("i").css({cursor:"pointer"});e=l.outerWidth()-1;d=l.outerHeight();var n=m.outerWidth(),p=m.outerHeight();switch(b){case "left":m.css({left:h[0]-n-e+"px",top:Math.floor(h[1]-p/2)+"px"});l.css({top:Math.floor((p-
d)/2)+"px",right:-e+"px"});c.css({top:"0px",left:"2px"});break;case "right":m.css({left:h[0]+e+"px",top:Math.floor(h[1]-p/2)+"px"});l.css({top:Math.floor((p-d)/2)+"px",left:-e+"px"});c.css({top:"1px",right:"2px"});break;case "top":m.css({left:Math.floor(h[0]-n/2)+"px",top:h[1]-p-d+"px"});l.css({left:Math.floor((n-e)/2)+"px",top:p-1+"px"});c.css({top:"1px",right:"2px"});break;case "bottom":m.css({left:Math.floor(h[0]-n/2)+"px",top:h[1]+d+"px"}),l.css({left:Math.floor((n-e)/2)+"px",top:-d+"px"}),c.css({top:p-
3-c.outerHeight()+"px",right:"1px"})}b=function(a){a.stopPropagation()};var r=function(){q&&(clearTimeout(q),q=null);m&&(m.css({opacity:0}).del(),m=null);a(window).unbind("resize",r).unbind("scroll",r);a(document).unbind("mousedown",r).unbind("mouseup",r).unbind("CLEAR_MASK")},v=function(){m.css("opacity",0);q=setTimeout(r,1E3)};m.data("destroy",r);q=setTimeout(v,k);m.css({opacity:1}).bind("mousedown",b).bind("mouseup",b).bind("mouseenter",function(){q&&(clearTimeout(q),q=null)}).bind("mouseleave",
function(){q=setTimeout(v,k)});a(window).one("resize",r).one("scroll",r);a(document).one("mousedown",r).one("mouseup",r);c.one("click",r)}}});a.fn.Tips=function(c,b,d,g,k){c=c?c:"mouseenter";var h=a(this);d=d?d:"right";h.bind(c,function(){a.closetips();a.tips(h,d,b,g);if(!k)h.unbind("mouseleave").one("mouseleave",a.closetips)})};a.fn.ZoomBigPic=function(){a(this).unbind("click").bind("click",function(){var b=a(this).is("img")?a(this):a(this).find("img:eq(0)"),d=b.attr("src"),b=b.attr("title");d&&
new showPopBigPic(d,b);return!1})};a.fn.getFitSize=function(b,d){b=b?b:4/3;d=d?d:60;var e=a(this);e.width("auto").height("auto");var g=e.width();if(g<=d)e.width(d);else{for(;e.width()/e.height()>b;)if(g-=10,g<=d){e.width(d);break}else e.width(g);e.css("overflow-y","auto")}}})(jQuery);
function popMask(a,d){function b(a){a.stopPropagation();a.preventDefault()}function c(){if(f.mask){var a=$(window).width(),b=$(window).height();f.mask.width(a).height(b)}else f.destroy()}var f=this;this.mask=$('<div class="fm_Mask"></div>');this.mask.data("obj",f);this.name=d||"mask";this.install=function(){$("body").append(f.mask);f.mask.hide().css({position:"fixed",top:"0px",left:"0px","z-index":a||999});c();f.mask.fadeIn("normal");$(window).bind("resize",c).one("CLEAR_MASK",f.destroy);f.mask.bind("mousewheel",
b)};this.hide=function(){f.mask.stop(!0,!0).hide()};this.show=function(){f.mask.stop(!0,!0).show()};this.destroy=function(){$(window).unbind("resize",c).unbind("CLEAR_MASK",f.destroy);f.mask&&(f.mask.unbind(),f.mask.fadeOut("normal",function(){f.mask.remove();f.mask=null}))};this.install()}
function CenterInWindow(a,d){function b(){g&&(clearTimeout(g),g=null);g=setTimeout(c,100)}function c(){var b=$(window).width(),c=$(window).height();"string"==typeof d[0]?e[0]="right"==d[0]?b-a.outerWidth(!0):0:(e[0]=1<d[0]?d[0]:b*d[0],e[0]-=a.outerWidth(!0)/2);"string"==typeof d[1]?e[1]="bottom"==d[1]?c-a.outerHeight(!0):0:(e[1]=1<d[1]?d[0]:c*d[0],e[1]-=a.outerHeight(!0)/2);e[1]=0<e[1]?e[1]:0;f?a.css({left:Math.floor(e[0])+"px",top:Math.floor(e[1])+"px"}):a.stop().animate({left:Math.floor(e[0])+"px",
top:Math.floor(e[1])+"px"},500)}var f=!0,e=[];this.install=function(){d=d?d:[.5,.5];a.css({position:"fixed"});c();f=!1;$(window).bind("resize",b)};this.destroy=function(){$(window).unbind("resize",b)};var g;this.install()}
function popOutSelfMsg(a,d,b,c,f){var e,g,k,h=this,q,l=f||getIndex("tips");this.show=function(){h.destroy();c||(g=new popMask(l-1));e=$('<div id="fm_popMsgContainer"></div>');e.css({position:"fixed","z-index":l,"min-height":"40px","min-width":"40px","background-color":"#fff","border-radius":"6px",padding:"8px","box-shadow":"0px 0px 3px #666",overflow:"auto"});$("body").append(e);e.append(a);b&&e.setRealSize(b[0],b[1]);q=new CenterInWindow(e);e.data("msgobj",h).hide().fadeIn("slow");$(document).one("HIDE_MSG",
h.destroy);d&&0<d&&(k=setTimeout(h.destroy,d));return e};this.destroy=function(){$(document).unbind("HIDE_MSG",h.destroy);k&&(clearTimeout(k),k=null);q&&q.destroy();e&&(e.del(),e=null);g&&(g.destroy(),g=null)};h.show()}
function loadingRoll(){function a(){b.css("background-position","center "+-40*f+"px");f=(f+1)%12}var d,b,c,f=1,e,g=this,k;this.show=function(e){g.destroy();e||(c=new popMask(getIndex("loadingMask")));b=$('<div id="fm_loading"></div>');b.css({position:"fixed","z-index":"9999",height:"40px",width:"40px","background-color":"#000","border-radius":"8px",opacity:"0.7","background-repeat":"no-repeat","background-position":"center 0px",overflow:"hidden"});$("body").append(b);k=new CenterInWindow(b);b.data("loadobj",
g).hide().fadeIn("slow");d=setInterval(a,66);$(document).one("HIDE_LOADING",g.destroy)};this.progress=function(a){var c=b.find(".fm_progress");0==c.length&&(c=$('<div class="progressBar"><div></div></div>'),b.append(c),b.css({overflow:"visible"}),c.css({position:"relative",height:"20px"}).find(">div").css({position:"absolute","text-align":"center",margin:"0px",padding:"3px","padding-left":"15px","padding-right":"15px","border-radius":"15px","line-height":"18px",color:"#fff","background-color":"#000",
opacity:1,top:b.height()+10+"px","min-width":"140px","max-width":"600px"}));c.find(">div").text(a);c.find(">div").css({left:-Math.floor((c.find(">div").outerWidth()-b.outerWidth())/2)+"px"})};this.destroy=function(){$(document).unbind("HIDE_LOADING",g.destroy);e&&(clearTimeout(e),e=null);k&&k.destroy();b&&(b.del(),b=null);c&&(c.destroy(),c=null);d&&(clearInterval(d),d=null)}}
function LoadingProgress(a,d){var b;this.showLoading=function(){$("#fm_loadingbar").del();b||(b=$("<div id='fm_loadingbar'></div>"),$("body").append(b),b.addClass("waiting"));b.show().width(50+30*Math.random()+"%")};this.progress=function(){b&&b.width("101%").delay(200).fadeOut(400,function(){b.hide().width(0)})};this.destroy=function(){b&&(b.remove(),b=null)}}
function showPopBigPic(a,d){function b(){switch($(this).attr("id")){case "rotationRight":p+=90;p=360==p?360:p;g.css({transform:"rotate("+p+"deg)"});break;case "rotationLeft":p-=90;p=360==p?360:p;g.css({transform:"rotate("+p+"deg)"});break;case "closePicBut":e.destroy()}}function c(a,b){var c=$(this),d=0==p%180,e=c.width(),f=c.height(),g=parseInt(c.css("left").replace("px","")),k=parseInt(c.css("top").replace("px","")),h=Math.floor(c.width()*(1+.1*b)),h=32>h?32:h;c.width(h);c.height("auto");var l=
c.height();d?c.css({left:g-Math.floor((h-e)/2)+"px",top:k-Math.floor((l-f)/2)+"px"}):c.css({left:g-Math.floor((l-f)/2)+"px",top:k-Math.floor((h-e)/2)+"px"});return!1}function f(){window.open(a)}var e=this,g,k,h,q,l,m,n,p=0;this.install=function(){q=new popMask(getIndex("image"));g=$('<img src="'+a+'"/>');g.css({position:"fixed",border:"1px solid #CCC","box-shadow":"2px 2px 8px #666666","z-index":getIndex("image")+1,opacity:0,transition:"opacity 0.5s,transform 0.5s","background-color":"#fff"});$("body").append(g);
if(supportCss("transform")||d){n=$('<div class="bigPicTitle">'+(supportCss("transform")?'<a id="rotationLeft"><i class="fa fa-undo"></i></a><a id="rotationRight"><i class="fa fa-repeat"></i></a>':"")+'<a id="closePicBut"><i class="fa fa-remove"></i></a></div>');n.css({position:"fixed",bottom:"0px",left:"0px",right:"0px",padding:"4px","z-index":getIndex("image")+2,"text-align":"center","background-color":"#333",opacity:.8});n.find("a").css({"border-radius":"120px",color:"#FFF","font-size":"16px",padding:"4px",
"line-height":"22px","background-color":"#000","margin-left":"3px",display:"inline-block",width:"22px",height:"22px","vertical-align":"middle"}).bind("click",b);if(d){var h=$("<div>"+d+"</div>");n.prepend(h);h.css({"border-radius":"120px",color:"#CCC",padding:"4px","line-height":"22px","background-color":"#000",margin:"auto","padding-left":"30px","padding-right":"30px",display:"inline-block","max-width":"70%","vertical-align":"middle"})}$("body").append(n)}else l=$('<div class="closePicBut"></div>'),
q.mask.append(l);q.mask.bind("click",e.destroy);g.bind("dblclick",f);g.bind("load",e.resetSize);g.bind("mousewheel",c);g.fadeIn("normal");$(window).bind("resize",e.resetSize);m=new dragDivObj;m.install(g,g)};this.resetSize=function(){k=$(window).width();h=$(window).height();var a=g.width(),b=g.height(),c=k/h,d=Math.floor(.9*k),e=Math.floor(.9*h),f=Math.floor(k*(1-.9)/2),p=Math.floor(h*(1-.9)/2);a<=d&&b<=e?g.height(b).width(a).css({left:Math.floor((k-g.width())/2)+"px",top:Math.floor((h-g.height())/
2)+"px"}):a/b<c?g.height(e).width("auto").css({left:Math.floor((k-g.width())/2)+"px",top:p+"px"}):g.width(d).height("auto").css({top:Math.floor((h-g.height())/2)+"px",left:f+"px"});g.css("opacity",1)};this.destroy=function(){$(window).unbind("resize",e.resetSize);g.unbind().fadeOut("normal",function(){g.del()});n&&(n.del(),n=null);q.destroy();m.destroy()};this.install()}
function creatPostParam(a,d,b,c){a={event:a,extend:{},content:{}};a.content.condition=d||{};a.content.value=b||{};a.extend=c||{};return a}function formatPostParam(a){for(var d in a)a[d]="string"==typeof a[d]?a[d]:JSON.stringify(a[d]);return a}function formatHostJson(a){if(a){if(a.value)return a.value;checkResponse(a);return a}return null}function sessionListener(){$.ajaxSetup({global:!0,beforeSend:formatPostVars});$(document).ajaxSuccess(function(a,d){checkResponseStatus(d)})}
function formatPostVars(a,d){0>d.url.toLowerCase().indexOf(".html")&&(d.url+=0>d.url.indexOf("?")?"?project="+projectName:"&project="+projectName)}function checkResponseStatus(a){if(a=a.responseText+""){if("string"==typeof a)try{a=JSON.parse(a)}catch(d){return!0}checkResponse(a)}return!0}
function checkResponse(a,d){if(isNull(a.head)||isNull(a.head.code))return $.message("\u8fd4\u56de\u6570\u636e\u683c\u5f0f\u9519\u8bef!"),!1;if("1"==a.head.code+"")return a.head.message?$.message(a.head.message,2E3):null,!0;switch(a.head.code+""){case "0":d?null:$.errormsg(a.head.message||"\u64cd\u4f5c\u5931\u8d25!");break;case "3":d?null:$.message(a.head.message||"\u64cd\u4f5c\u672a\u5b8c\u6210",2E3);break;case "8":$.message(a.head.message||"\u65e0\u6743\u64cd\u4f5c",2E3);break;case "9":logoutDeal(9)}return!1}
function AJAXObj(){function a(a,b){f&&f.destroy();c.destroy();if("success"==a.status||"200"==a.status)"parsererror"==b&&($(c).trigger("SYS_ERROR","\u8fd4\u56de\u6570\u636e\u89e3\u6790\u5931\u8d25!"),c.silent?null:$.message("\u8fd4\u56de\u6570\u636e\u89e3\u6790\u5931\u8d25!",2E3));else switch(a.status.toString()){case "0":$(c).trigger("SYS_ABORT","\u8bf7\u6c42\u88ab\u7ec8\u6b62");break;case "404":$(c).trigger("SYS_ERROR","\u7cfb\u7edf\u9519\u8bef404");c.silent?null:$.message("\u7f51\u7edc\u9519\u8bef\uff0c\u53ef\u80fd\u7f51\u7edc\u4e0d\u901a!",
2E3);break;case "500":$(c).trigger("SYS_ERROR","\u7cfb\u7edf\u9519\u8bef500");c.silent?null:$.message("\u670d\u52a1\u5668\u9519\u8bef!",2E3);break;default:$(c).trigger("SYS_ERROR","\u7cfb\u7edf\u9519\u8bef"),c.silent?null:$.message("\u672a\u77e5\u7f51\u7edc\u9519\u8bef!",2E3)}}function d(a){checkResponse(a,!0)?$(c).trigger("JSON_LOADED",a):$(c).trigger("SYS_ERROR",a.head.message)}function b(a,b){0>b.url.toLowerCase().indexOf(".html")&&(b.url+=0>b.url.indexOf("?")?"?project="+projectName:"&project="+
projectName);f.showLoading()}var c=this;this.isasync=!0;this.silent=!1;this.timeout=6E4;var f=new LoadingProgress,e;this.Post=function(a,b){c.POSTDATA(a,b)};this.POSTDATA=function(g,k){c.destroy();if(k)for(var h in k)"object"==typeof k[h]&&(k[h]=JSON.stringify(k[h]));e=$.ajax({type:"post",dataType:"json",data:k||{},url:g,async:c.isasync,complete:a,timeout:c.timeout,success:d,beforeSend:b}).always(f.progress)};this.destroy=function(){e&&($(e).unbind(),e.abort(),e=null)};this.GetHtml=function(b,d){if(!useCache){var e=
new Date,e=e.getTime();b+=0>b.indexOf("?")?"?i="+e:"&i="+e}$.ajax({type:"get",dataType:"html",url:b,async:c.isasync,complete:a,success:function(a){0==a.indexOf("{")?(a=JSON.parse(a),checkResponse(a)):$(c).trigger("HTML_LOADED",a)},beforeSend:f.showLoading}).always(f.progress)}}
function LoadHtml(a,d,b){var c=new AJAXObj;c.silent=!0;$(c).one("HTML_LOADED",function(a,d){d=trim(d+"");var g=d.substr(0,1);if("{"==g||"["==g)try{var k=JSON.parse(d);checkResponse(k)}catch(h){}else c.destroy(),c=null,b(a,d)}).one("SYS_ERROR",function(d,e){c.destroy();c=null;b(null,'<script type="text/javascript">function ACTION(){this.READY=function(){}}\x3c/script><div class="fm_e404"><h1>:( <span>\u51fa\u9519\u5566~~</span></h1><p>\u60a8\u8bbf\u95ee\u7684\u9875\u9762\u4e0d\u5b58\u5728\uff0c\u8bf7\u68c0\u67e5\u914d\u7f6e\u6587\u4ef6\u3002</p><p>URL: '+
a+"</p></div>")});c.GetHtml(a)}
function ajaxGetSelectOption(a,d,b,c){var f=function(){"select"==d?a.empty().append($("<option>--\u6570\u636e\u9519\u8bef--</option>")).addClass("errorload"):a.after($("<span>\u6570\u636e\u9519\u8bef</span>")).remove();b()},e=function(e,f){var g=f.value,l=a.attr("name");switch(d){case "select":l="";if(0==g.length)l+='<option value="" selected="selected">\u65e0</option>';else{a.hasClass("fm_forSelect")?l+='<option value="" selected="selected">\u8bf7\u9009\u62e9</option>':a.hasClass("fm_selectAll")&&
(l+='<option value="" selected="selected">\u5168\u90e8</option>');var m="";c["default"]&&("object"==typeof c["default"]?(l+='<option value="'+c["default"].value+'" selected="selected">'+c["default"].text+"</option>",m+=c["default"].value+","):m+=c["default"]+",");for(var n=0;n<g.length;n++){var p="";g[n].selected&&(p='selected="selected"',m+=g[n].value+",");l+='<option value="'+g[n].value+'" '+p+">"+g[n].text+"</option>"}m=0<m.length?m.substr(0,m.length-1):g[0].value}a.empty().append($(l));m=1==c.mulit?
"string"==typeof m?m.split(","):m:"string"==typeof m?m.split(",")[0]:m;a.val(m);break;case "radio":p="";m=[];c["default"]&&(m="string"==typeof c["default"]?c["default"].split(","):c["default"]);for(n=0;n<g.length;n++)g[n].selected&&m.push(g[n].value),p+='<label><input type="radio" name="'+l+'" id="'+l+"_"+n+'" value="'+g[n].value+'" />'+g[n].text+"</label>";g=$(p);a.after(g).remove();g.find(">input").val(m);break;case "checkbox":p="";m=[];c["default"]&&(m="string"==typeof c["default"]?c["default"].split(","):
c["default"]);for(n=0;n<g.length;n++)g[n].selected&&m.push(g[n].value),p+='<label><input type="checkbox" name="'+l+'" id="'+l+"_"+n+'" value="'+g[n].value+'" />'+g[n].text+"</label>";g=$(p);a.after(g).remove();g.find(">input").val(m);break;default:a.data("selectdata",g)}b()};if(c){var g=c.param;LoadListData(c,a.attr("name"),g,e,f)}else f()}
function LoadListData(a,d,b,c,f){a&&a.url?(a=a.url,b=$.extend({selecFieldName:d},b||{}),d=creatPostParam(d,b),b=new AJAXObj,b.silent=!0,$(b).one("JSON_LOADED",c).one("SYS_ERROR",f),b.POSTDATA(a,d)):f()}function callHost(a,d){$.ajax({type:"post",data:formatPostParam(d||{}),url:a,async:!0})}
function loginPage(){function a(){$(".login").css({"margin-top":Math.floor($(window).height()/2)+"px"});$("body").height($(window).height()-2);b(!0);$(".loginbox input[type='text']").bind("focus",q).bind("blur",d)}function d(){var a=$(this).val()+"";""==h(a)&&("u_name"==$(this).attr("name")?$(this).removeClass("blackText").val("\u8bf7\u8f93\u5165\u7528\u6237\u540d"):"u_pass"==$(this).attr("name")&&(browserIsIE8||browserIsIE7||browserIsIE6?(a=$('<input name="u_pass" type="text"  class="pws" id="u_pass"  value="\u8bf7\u8f93\u5165\u5bc6\u7801" size="100"/>'),
$(this).after(a).remove(),a.bind("focus",q).bind("blur",d)):$(this).attr("type","text").removeClass("blackText").val("\u8bf7\u8f93\u5165\u5bc6\u7801")))}function b(a){var c=function(){$("body").height($(window).height()-2);var c=$(window).height(),d=$(".login").height(),c=Math.floor((c-d)/2);0>c&&(c=0);1==a?($(".login").stop().animate({"margin-top":c+"px"},500),$(window).bind("resize",b)):$(".login").stop().animate({"margin-top":c+"px"},500);600>$(window).height()?$(".foot").hide():$(".foot").show()};
browserIsIE6?(n&&clearTimeout(n),n=setTimeout(c,100)):c()}function c(a){a&&$("p.sys").fadeIn("slow").find("span").text(a)}function f(){$("input").bind("focus",function(){$("p.error").stop().fadeOut("fast");$(this).parent().addClass("focus")}).bind("blur",l);$(document).unbind().bind("keypress",k);$("#loginbut").unbind().bind("click",e).get(0).disabled=!1}function e(){var a=!0,b=h($("#u_name").val()),d=h($("#u_pass").val());if("text"==$("#u_pass").attr("type")||""==d)$("p.upws").fadeIn("slow").find("span").text("\u8bf7\u8f93\u5165\u5bc6\u7801"),
a=!1;if(""==b||"\u8bf7\u8f93\u5165\u7528\u6237\u540d"==b)$("p.uname").fadeIn("slow").find("span").text("\u8bf7\u8f93\u5165\u7528\u6237\u540d"),a=!1;a&&($("#loginbut").addClass("disable"),$("#loginbut").get(0).disabled=!0,$(document).unbind("keypress",k),a=loginPort,d=creatPostParam("LOGIN",{userId:b,password:d,clientType:"1"},{eventswitch:"submit"}),$("#loginbut").removeClass("disable").get(0).disabled=!1,$(document).unbind().bind("keypress",k),$(m).one("JSON_LOADED",g).one("SYS_ERROR",function(a,
b){c("\u767b\u5f55\u5931\u8d25,"+b+".")}),m.POSTDATA(a,d),addCookie("savedUsername",b,8760))}function g(a,b){$("#loginbut").removeClass("disable").get(0).disabled=!1;$(document).unbind().bind("keypress",k);var d=b.value.status;"ok"==d?window.location="index.html":c("\u767b\u5f55\u5931\u8d25,"+d+".")}function k(a){a=a||window.event;13==(a.keyCode||a.which)&&e()}function h(a){return(a+"").replace(/(\s+)$/g,"").replace(/\s+/g,"")}function q(){if(!$(this).hasClass("blackText")&&($(this).addClass("blackText").val("").unbind("click"),
$(this).hasClass("pws")||"u_pass"==$(this).attr("name")))if(browserIsIE8||browserIsIE7||browserIsIE6){var a=$('<input name="u_pass" type="password"  class="pws" id="u_pass"  value="" size="100"/>');$(this).after(a).remove();a.focus().bind("focus",function(){$("p.error").stop().fadeOut("fast");$(this).parent().addClass("focus")}).bind("blur",l).bind("blur",d)}else $(this).attr("type","password")}function l(){$(this).parent().removeClass("focus")}var m=new AJAXObj,n;this.install=function(){$("body").html('<div class="login"><div  class="loginbox"><div class="input nam"><input name="u_name" type="text" id="u_name" value="\u8bf7\u8f93\u5165\u7528\u6237\u540d" maxlength="100"/></div><div class="input pws"><input name="u_pass" type="text"  class="pws" id="u_pass"  value="\u8bf7\u8f93\u5165\u5bc6\u7801" size="100"/></div><div class="but"><input type="button" value=" " id="loginbut"/></div><p class="error uname"><span></span></p><p class="error upws"><span></span></p><p class="error sys"><span></span></p> </div></div><div class="foot"><h1></h1><div class="addInfo"></div><p class="copy"></p></div>');
document.title=projectTitle;$(".foot h1").html(projectTitle);$(".foot p").text(projectCopyRight);"undefined"!=typeof loginAddinfo&&loginAddinfo?$(".foot .addInfo").html(loginAddinfo):$(".foot .addInfo").remove();$(document).ready(a);$(document).ready(f);var b=getCookie("savedUsername");b&&$("#u_name").addClass("blackText").val(b)};this.destroy=function(){$(document).unbind("ready",a);$(document).unbind("ready",f)}};